#!/bin/bash -l
#SBATCH -N 1        
#SBATCH --time=2:00:00
#SBATCH --job-name=cluster_lidar
#SBATCH -n 1
#SBATCH --mail-user=rjackson@anl.gov
# Environment variables

export MPLBACKEND="agg"

conda activate pydda_env
cd /lcrc/group/earthscience/rjackson/e3sm_nsa/scripts
python make_microbase_old_daily.py 2007 $SLURM_ARRAY_TASK_ID

