#!/bin/bash -l
#SBATCH -N 1        
#SBATCH --time=4:00:00
#SBATCH --job-name=cluster_lidar
#SBATCH -n 1
#SBATCH --mail-user=rjackson@anl.gov
# Environment variables

export MPLBACKEND="agg"

conda activate pydda_env
cd /lcrc/group/earthscience/rjackson/e3sm_nsa/scripts
python make_nsa_interpsonde_avgs.py
